name: Deploy Lambda Function

on:
  push:
    branches:
      - main  # Change this if using a different branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.8'

      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli

      - name: Install dependencies
        run: |
          pip install boto3

      - name: Deploy Lambda Function
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: |
          zip lambda_function.zip lambda_function.py
          aws lambda update-function-code --function-name VisitorCounter \
            --zip-file fileb://lambda_function.zip \
            --region $AWS_REGION
